name: Check Resources

on: [push,pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Run Checks
      #  shell: bash +e +o pipefail {0}
        run: |
          gem install awesome_bot
          awesome_bot -f README.md --allow-ssl --allow 302,429 --white-list firsttimersonly.com,github.com/github,creativecommons.org/licenses/by-sa/4.0,@kentcdodds,kentcdodds.com/blog/what-open-source-project-should-i-contribute-to
          gem install danger

      # - name: Run Danger
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   uses: danger/danger@master
